### ISSUE TITLE
Mobile Devices

### ISSUE THREAD

**Issue by Sartorius7380** [Robdel12/DropKick#241]
I am having an issue with dropkick.js not rendering properly on mobile devices.  On desktops it seems to be working fine, great in fact, but when I tested the site on a kindle fire, samsung galaxy s3, and most iphone it does not show any of the styling on the phones and it is almost completely broken on the kindle.  The staging site I am working on is bbdemo.book.com.  I was wondering if you could by chance take a look and let me know if there is some issue I am not catching.  Also, I did change the script for mobile devices.  Any help would be appreciated.

Thanks,
Derick

Update...Scratch the cell phone issue, I figured out what I was doing wrong, but it still has issues on the Kindle Fire.  It does not seem to render the objects portion of the drop down.  It shows top section and when touched it acts like it is dropping down a list, but it is a blank area.

**Comment by riyaja** [comment]
I have the same issue on Ipad and Iphone with dropkick version 1.0.Please update on this

**Comment by Robdel12** [comment]
Hi @riyaja. Dropkick 1.0 is _extremely_ old, is there any specific reason you're still using 1.x and not 2.x?

**Comment by riyaja** [comment]
@Robdel12  actually it is part of existing app.Unfortunately I can not upgrade to newer version.I need  to fix the issue with this verson
