### ISSUE TITLE
Migration guide from DK 1 to 2

### ISSUE THREAD

**Issue by raffomania** [Robdel12/DropKick#260]
Is there a possibility to create this? Even just a short list of breaking changes would be life saving. I found nothing like a changelog for version 2 :(

**Comment by adayth** [comment]
First off, thank you for this nice plugin.

Can you provide some advices / guidelines in this issue?

I need to upgrade dropkick 1.4 to latest version from a Wordpress theme with custom styles and scripts and need some advices.

**Comment by Robdel12** [comment]
Honestly I can't offer very much advice right now. I'd need to set up a "legacy demo" and try to upgrade from there. I know @wwilsman built 2.x in mind of users upgrading from 1.x. 

If anyone wants to champion this I'd appreciate it! :D Otherwise I'll try to carve out some time for this.

**Comment by wwilsman** [comment]
The major thing you'll have to do while upgrading from 1.x is re-style and re-theme Dropkick. Start with dropkick.css and modify it until Dropkick looks the same as before you upgraded. If you have multiple themes, just add classes to your selects, which can then be used for targeting specific Dropkick elements (e.g. `.dk-select.custom`).

I've never personally used 1.x, but if you run into any javascript-related bugs after you upgrade, let us know.

**Comment by Robdel12** [comment]
I'm going to close this issue since we're so far removed from DK 1.x.
