### ISSUE TITLE
iFrame tests need to be reworked

### ISSUE THREAD

**Issue by Robdel12** [Robdel12/DropKick#264]
I've been fiddling with these tests for sometime now. I think it's time we just rewrite them and call it a day.

**Comment by TJkrusinski** [comment]
[This commit](https://github.com/Robdel12/DropKick/commit/273fb70b22c8cf20a5e97a842e954f251a1c6797#diff-13d3ac305a9a6f002edfa9c605c23f9aR7) seems to just call the same document in the iframe no? Looked like previous commits tried to reach into the parent, did that not work?

Also I'm not super familiar with how events propagate up and down iframes to and from parents fyi.

**Comment by Robdel12** [comment]
Yeah I remember having issues with creating a click. For what its worth I can recreate the scenario and confirm DK works outside of the testing world. 

I think this all falls apart when we need to simulate the click. I'm just unfamiliar with the whole process so I could be wrong.

**Comment by Robdel12** [comment]
@cforrester do you have any ideas? :D

**Comment by kipusoep** [comment]
I was just looking for an existing issue about the line:
```isIframe = (window.parent !== window.self && location.host === parent.location.host)```

It's throwing errors while running in an iframe, so I just disabled it for now:
```isIframe = false```

**Comment by bsthomsen** [comment]
I've experienced similiar issue like @kipusoep I've resolved it temporarely by making a custom build of dropkick with `isIframe = false`.

**Comment by andreschaefer** [comment]
http://stackoverflow.com/questions/21751377/foolproof-way-to-detect-if-this-page-is-inside-a-cross-domain-iframe

**Comment by Robdel12** [comment]
This was closed with #346 (https://github.com/Robdel12/DropKick/blob/master/tests/dropkick-test.js#L240)
