### ISSUE TITLE
IE8-11 drop downs always open with "dk-option-open-down"

### ISSUE THREAD

**Issue by Vyygir** [Robdel12/DropKick#267]
I'm using Dropkick for a project I'm working on and whenever I open a drop down in IE8 through to 11 the "dk-option-open-down" class is added, even if the contents go past the bottom of the document.

**Comment by Robdel12** [comment]
![screen shot 2015-01-23 at 10 11 52 am](https://cloud.githubusercontent.com/assets/2072894/5876825/53cf7af0-a2e8-11e4-9d81-878c54554416.png)
![screen shot 2015-01-23 at 10 11 12 am](https://cloud.githubusercontent.com/assets/2072894/5876826/53e808a4-a2e8-11e4-9a75-af0aad9acd63.png)

These screen shots are IE9. Have some styling issues too

**Comment by Vyygir** [comment]
I've played about with the code a bit today and come up with a few potential fixes.

Change line 354 to the following:
```
dkTop = _.offset( dk ).top - document.documentElement.scrollTop,
```

Change lines 111 - 114 to the following:
```
return {
  top: box.top + docElem.scrollTop - docElem.clientTop,
  left: box.left + docElem.scrollLeft - docElem.clientLeft
};
```
