### ISSUE TITLE
TypeError: undefined is not an object on iOS

### ISSUE THREAD

**Issue by anthonycollini** [Robdel12/DropKick#268]
When using Dropkick.js on the iPad (iOS), the initial selection from a select works, however, after trying to select a different value, the following error is produced:

`TypeError: undefined is not an object (evaluating 'this.data.select')`

Converting the select to a regular ember select removes the issue. We are using Dropkick 2.1 in ember through bower using `"dropkick": "git://github.com/Robdel12/DropKick.git#v2.1"`

**Comment by Robdel12** [comment]
What version of iOS?

**Comment by anthonycollini** [comment]
I am on iOS 8.1.

I also updated to `"ember-dropkick": "0.0.4"` and it didn't fix the issue.

**Comment by Robdel12** [comment]
Hop on Slack?

**Comment by Robdel12** [comment]
Any more info on this? I can't replicate on my iPad with iOS 8.1 or any iOS device

**Comment by Robdel12** [comment]
Closing this since we can't replicate

**Comment by anthonycollini** [comment]
This can definitely still be reproduced on all iPad versions and the Xcode simulators. We ended up just not using dropkick for iPad, doing a user agent check.

**Comment by Robdel12** [comment]
This is an issue when *not* using DropKick on mobile and using *native* selects. Reopening.

**Comment by anthonycollini** [comment]
No, native selects work fine. It's only when Dropkick is added. If you can't reproduce it, perhaps it has to do with something in my codebase conflicting with Dropkick. I'll have to do some more debugging when I have some time.

**Comment by Robdel12** [comment]
This is related to ember-dropkick. So I'm going to close this issue and open it up on the ember-dropkick repo.
