### ISSUE TITLE
Cannot read property 'data' of undefined after using refresh

### ISSUE THREAD

**Issue by nkovacs** [Robdel12/DropKick#273]
This line here has an error:
https://github.com/Robdel12/DropKick/blob/v2.1.2/dropkick.js#L37
because dispose can delete elements from the array:
https://github.com/Robdel12/DropKick/blob/v2.1.2/dropkick.js#L615

**Comment by wwilsman** [comment]
Pretty good timing, I just pushed a fix for this.

**Comment by Robdel12** [comment]
Heh, yea we just saw this. 2.1.3 should fix this :)

**Comment by nkovacs** [comment]
It does, thanks.
