### ISSUE TITLE
fuzzy search yields undefined

### ISSUE THREAD

**Issue by artknight** [Robdel12/DropKick#275]
Line 122: elem is undefined

Seems that when setting search to 'fuzzy', undefined is returned in the matched results.

**Comment by Robdel12** [comment]
Intersting. I [wrote some[(https://github.com/Robdel12/DropKick/commit/15d66fbb98df0443bb3c79806abd2a7e0de144f1) tests for fuzzy, partial, and strict searching to see if I could reproduce. 

Can you provide a JSBin?

**Comment by Robdel12** [comment]
Going to close this. I'll reopen if I can get a reproducible error :)
