### ISSUE TITLE
IE8 Object doesn't support this property or method

### ISSUE THREAD

**Issue by adrianosmond** [Robdel12/DropKick#278]
I can't see browser support anywhere on here, but from other issues filed it looks like IE8 is in scope for DropKick?

I'm getting an "Object doesn't support this property or method" error in IE8 any time I select anything in DropKick. This is both in my own code and in the examples on http://robdel12.github.io/DropKick/

IE8 tells me this error is being caused by document.createEvent (which I don't think is supported in IE8). It looks like this is being called by the polyfill you've used for CustomEvent, which if it's this one as it looks like it is: https://github.com/krambuhl/custom-event-polyfill/blob/master/custom-event-polyfill.js, doesn't support IE8 (only IE9+).

**Comment by Robdel12** [comment]
Thanks @adrianosmond for the issue! 
"I can't see browser support anywhere on here, but from other issues filed it looks like IE8 is in scope for DropKick?"

Yes, IE8 + is what we shoot to support. I've been trying to get a much better docs page going but I've been busy lately :/

I/we will definitely look into this today and hopefully ship a fix!

**Comment by Robdel12** [comment]
@adrianosmond can you give this a shot on master? I'd like to verify before cutting 2.1.4

**Comment by Robdel12** [comment]
Closing this as it should have been fixed with https://github.com/Robdel12/DropKick/commit/d1b348563d0e4bf775b90be1d275bc9513caf0d3
