### ISSUE TITLE
select option programmatically

### ISSUE THREAD

**Issue by artknight** [Robdel12/DropKick#279]
As far as i know, the only way to select an option programmatically is to call `this.select('option')`.
So, to pre-select an option I have to do this

```javascript
$('#some-select').dropkick({
   initialize: function(){
       this.select('option');
   }
});
```
Suggestion:
It would be great if an option existed similar to this
`$('#some-select').dropkick({ select:'option' });`

...just a thought.

**Comment by wwilsman** [comment]
Have you tried just adding the [selected](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option#attr-selected) attribute to the option?

**Comment by artknight** [comment]
yes, it does work, but I do need to select it after the select has loaded.

**Comment by wwilsman** [comment]
How about using jQuery to select it before calling Dropkick?

````
$('#some-select').val('option').dropkick();
````

**Comment by artknight** [comment]
Oh yeah, good idea :)

**Comment by wwilsman** [comment]
Glad I could help. :smile:
