### ISSUE TITLE
Having trouble setting the z-index property for the Dropkick element

### ISSUE THREAD

**Issue by ChayaCooper** [Robdel12/DropKick#290]
The z-index property for the DK dropdown appears to be higher than the Dropkick element, but I'm having trouble specifying the z-index properties for the Dropkick element and DK dropdown separately.  I've tried .dk_toggle and .dk_container, as well as .dk_options, .dk_open. 

I'm currently using Dropkick v. 1.0.0

**Comment by Robdel12** [comment]
Are you sure you are using DK 1.0.0? I'd highly recommend upgrading to at least 1.5.x to avoid any security issues. With that comes a bunch of CSS fixes, so let me know if that helps :)

If you have the bandwidth I'd update to the latest (2.1.x)

**Comment by ChayaCooper** [comment]
I realized that I was probably due for an update when I posted the question
;-) Unfortunately I think I should probably wait to change versions until
after my impending deadline because there's always a risk that the fixes
won't play nicely with something else (including some of the css I probably
used to work around some of those issues ;-))

Any chance you can help me out anyway :-) Or will I just have to wait until
I can upgrade it?

**Comment by Robdel12** [comment]
Sorry for the late reply! Did you get this sorted? 

Just spit balling here: make sure you have a position set on anything that a z-index is being applied to (like `position: relative;`)

If that doesn't work I'll try to find an old version of DK and help out :)

**Comment by Robdel12** [comment]
Going to close this. If you still need help we can reopen :)
