### ISSUE TITLE
Add responsive support

### ISSUE THREAD

**Issue by Purush0th** [Robdel12/DropKick#291]
Instead of fixed width is there any way to make dropdown responsive to adjust different view port?

**Comment by Robdel12** [comment]
You can do what you'd like with the CSS. :)

**Comment by Purush0th** [comment]
@Robdel12 Could you please provide some gist examples?

**Comment by arunsathyan01** [comment]
@Purush0th  try this 
.dk-select, .dk-select-multi {
  width: 100% !important; 
}

**Comment by Robdel12** [comment]
What @arunsathyan01 said with the addition if you change [this file](https://github.com/Robdel12/DropKick/blob/master/lib/css/dropkick.scss#L41) to what ever width you'd like. That way you don't need the `!important`.


```scss
.dk-select,
.dk-select-multi {
[..]
  width: 200px;
[..]
}
```
