### ISSUE TITLE
IE 11 Selected value is not reflecting in select control

### ISSUE THREAD

**Issue by arunsathyan01** [Robdel12/DropKick#292]
IE 11 Selected value is not reflecting in select control
Console Error: Object doesn't support this action
 File: dropkick.js, Line: 605, Column: 9

![image](https://cloud.githubusercontent.com/assets/9658680/7534763/5d2a5394-f59b-11e4-9a83-ef859e6644f2.png)

**Comment by wwilsman** [comment]
Check the value of the select in the console; the `selected` attribute only applies to options which are initially selected when the DOM loads.

**Comment by arunsathyan01** [comment]
i am using  2.1

Console error fixed with this code , 

var customevt =  document.createEvent('CustomEvent');
      if ( !disabled ) {
	     customevt.initCustomEvent('change',true,true,null);
             this.data.select.dispatchEvent(customevt);
      }

**Comment by wwilsman** [comment]
We've had quite a few problems with all IEs and that event bug. This will hopefully be getting fixed with the next release.

**Comment by Robdel12** [comment]
Closing this. Should be fixed with https://github.com/Robdel12/DropKick/commit/d1b348563d0e4bf775b90be1d275bc9513caf0d3
