### ISSUE TITLE
DropKick problem IE11 after postback

### ISSUE THREAD

**Issue by VinceBog** [Robdel12/DropKick#294]
I'm using DropKick in iframes and lately I have a problem only with IE11. After a page postback the default html select box is visible below the DropKick:
![image](https://cloud.githubusercontent.com/assets/12543924/7747542/b5d9fdc6-ffbb-11e4-98ec-b03da1e182fb.png)

After a mouse_click on the page - without a postback - the default html select box disappears:
![image](https://cloud.githubusercontent.com/assets/12543924/7747586/33d39e1c-ffbc-11e4-9b57-5214b0e9c176.png)

Does anyone knows a solution?

**Comment by VinceBog** [comment]
Has anyone a clue for a solution or work around?

**Comment by Robdel12** [comment]
I haven't had a chance to look into this. Gotta download a VM.

@wwilsman any ideas/suggestions?

**Comment by wwilsman** [comment]
Strange. I won't be able to test it myself until much later, but if you inspect the select element does it have the `data-dkcacheid` attribute? Is the attribute missing until you click? That's how the default styles determine to hide the select, and it should be set upon intialization.

If you find the attribute is missing, and you're using the default way to hide the select, try hiding it another way (e.g. `#myselect { display: none; }` or `.dk-select + select { display: none; }`).

**Comment by VinceBog** [comment]
Adding .dk-select + select { display: none; } in the css file solved the problem for ie. Thanks!

**Comment by wwilsman** [comment]
Glad to have helped. :+1:
