### ISSUE TITLE
Add demo example in dropkickjs.com

### ISSUE THREAD

**Issue by adayth** [Robdel12/DropKick#295]
API docs are ugly as homepage.
I think will be much better to have demo example as homepage, and the api as a secondary page.

**Comment by dreamingInCode** [comment]
Are there any demo's? I have no idea what this i supposed to achieve.

**Comment by Robdel12** [comment]
In the examples folder there's a demo.

**Comment by dancoates** [comment]
+1 for this. I was just trying to recommend dropkick to someone and didn't have anything to link them to to show what DropKick does.

**Comment by adayth** [comment]
Should be easy to move current dropkickjs.com content to dropkickjs.com/api or something like that and put the example instead.

The demo is really needed to show this great lib to the world. Please invest some time in this ;)

**Comment by Robdel12** [comment]
I'm currently busy with other stuff and haven't used DropKick in any of my current projects. It'll be a little hard to find time at the moment, but PRs are always welcome :)

**Comment by Robdel12** [comment]
Done in #305 :)
