### ISSUE TITLE
DK always expanded down on IE

### ISSUE THREAD

**Issue by tasiek** [Robdel12/DropKick#301]
Dropdown is always expanded down on IE. 

I've made a debug, the issue is quite simple: `window.scrollY` is used, but not supported on IE. To make it work, we need to change it to: `(window.scrollY || window.pageYOffset)`

**Comment by Robdel12** [comment]
Thanks for the issue! Do you happen to know what version of IE this is happening in?

**Comment by tasiek** [comment]
I'm pretty sure `window.scrollY` is not supported by any IE, and `window.pageYOffset` is a better, cross-browser alternative. Additionaly, for IE < 9 we need some additional effort.. Here are [some details](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY?redirectlocale=en-US&redirectslug=DOM%2Fwindow.scrollY).

**Comment by spoonben** [comment]
I actually haven't run into this issue, IE9+

**Comment by Robdel12** [comment]
I actually couldn't replicate this. Can you JSBin or gist up your code?

**Comment by kipusoep** [comment]
*sigh*
Running into this issue as well while we have DK fully implemented in one of our websites. FML

**Comment by Robdel12** [comment]
Removing the bug label until I can reproduce.

**Comment by Robdel12** [comment]
Can I get a bump on this? Also is anyone using requirejs?
