### ISSUE TITLE
mobile: true in the Doc but not in the API

### ISSUE THREAD

**Issue by Mushr0000m** [Robdel12/DropKick#306]
Hi,

Looking at the documentation page (http://dropkickjs.com/) I see in every examples "mobile: true" but on the API page (http://dropkickjs.com/api.html) this property doesn't exists. Is it an ommission in the API or an error on the doc ?

Thanks

**Comment by Robdel12** [comment]
Hi! Thanks for the issue. It looks like I missed adding it to the API doc. It's there for you to use, I just need to fix that :P

**Comment by Mushr0000m** [comment]
Nice thanks

**Comment by Robdel12** [comment]
http://dropkickjs.com/api.html#prop-mobile 🎉

**Comment by Mushr0000m** [comment]
Great thanks
