### ISSUE TITLE
Updating from DropKick 1.3.3 and I have issues

### ISSUE THREAD

**Issue by benlevywebdesign** [Robdel12/DropKick#308]
I decided to check up on DropKick to see if a new version was released. I was right and I am updating from DropKick **1.3.3** to **2.1.7.** The issue I had with [Dynamically created DropKick selects on a single page...](https://github.com/Robdel12/DropKick/issues/177) was resolved in DropKick **1.3.3** but, now with **2.1.7** I have a similar issue. I get a duplicate of the first DropKicked drop down on every dynamically created drop down as well as the working dropkick.

Here is the page where you can see it happen: [destinations_dropkicktest.php](http://benlevywebdesign.com/ontheway/destinations_dropkicktest.php)

[(This same page uses version 1.3.3 with no issues)](http://benlevywebdesign.com/ontheway/destinations_dropkicktest.php)

Here is my form select HTML code
```html
<div class="flex">
    <div class="flexbox flex">Set a location priority:</div>
    <div class="formsize">
        <div class="form-select">
        <select class="priority toggle-spinner" name="priority[1]">
        <option selected value="None">None</option>
        <option value="Low">Low</option>
        <option value="Medium">Medium</option>
        <option value="High">High</option>
        </select>
    </div>
    </div>
</div>
```
At the bottom of the page I include the link to `dropkick.2.1.7.min.js` along with the jQuery DropKick script:
```javascript
<script src="scripts/dropkick.2.1.7.min.js" type="text/javascript"> </script>
<script> $('.priority').dropkick({ mobile:true }); </script>
```

Now in my js file where I create the new destination this is what I have

```javascript
// DYNAMIC FORM DUPLICATION SCRIPT BELOW //
		
//Button and function to add destinations
	var count = 1;
	$('.action.bttn').on('click', function () {
			createNewDestination().hide().appendTo('#container').slideDown(500,"swing").find('.priority').dropkick({ mobile:true });
	});

//Create new destination and add count
	function createNewDestination() {
    count++;
	
//Create new content
	var newContent = $('<div/>', {
		html: GetHtml()
	});
//Add event handlers to new content
	newContent.find('#tripinfoid').attr('name', 'tripinfoid['+count+']');
	newContent.find('#tripinfoid').attr('id', 'tripinfoid' +count+'');
	newContent.find('[placeholder="Destination 1 address"]')[0].placeholder = "Destination " +count+" address";
	newContent.find('#destaddress').attr('id', 'destaddress' +count+'');
	newContent.find('#destaddress' + count).attr('name', 'destaddress['+count+']') ;
	newContent.find(".locations").geocomplete();
	newContent.find('[placeholder="Destination 1 name"]')[0].placeholder = "Destination " +count+" name";
	newContent.find('#destiname').attr('id', 'destiname' +count+'');
	newContent.find('#destiname' + count).attr('name', 'destiname['+count+']') ;
	newContent.find('#check').attr('id', 'check' +count+'');
	newContent.find('#scroller').attr('id', 'scroller' +count+'');

	newContent.find('.priority').attr('name', 'priority['+count+']');
	newContent.find('.priority .toggle-spinner').attr('id', 'priority' +count+'').unwrap().siblings().remove();

	console.log(newContent)
		return newContent;
	}
	
//GetHtml
	function GetHtml() {
		var $html = $('#dupcontent').clone();
		return $html.html();
	}
});
```

Thanks, Ben!

**Comment by wwilsman** [comment]
Hey Ben,

I think I see what's happening here, `#dupcontent` contains a Dropkick element. So when you clone the HTML, you're cloning the Dropkick HTML and then initializing a new Dropkick instance on the select, therefore creating additional HTML. You can see the clones start working if you remove the first Dropkick before clicking the button (type this into the console: `Dropkick.cache[0].dispose();`).

I might be able to work in a way to prevent this, but I'll need to look into it a little more and do some testing.

For now, you can get around this by caching `#dupcontent`'s HTML *before* you initialize the first Dropkick. Something like this:

````js
// cache html
var cachedHtml = $('#dupcontent').html();

// initialize first Dropkick
$('.priority').dropkick({ mobile: true });

/*... other code ...*/

//Create new content
var newContent = $('<div/>', {
  html: cachedHtml
});
````

Let me know if this helps

**Comment by benlevywebdesign** [comment]
@wwilsman, That was a quick response. I'll try it out. DropKick is awesome!

**Comment by benlevywebdesign** [comment]
@wwilsman, Your solution worked perfectly!

Thanks, 
Ben!

**Comment by benlevywebdesign** [comment]
The only thing left need to work out is that I get a color background on the select right as I tap on it on a mobile device. Its a light blue color or color of text selection on a mobile device...

**Comment by Robdel12** [comment]
@benlevywebdesign You should be able to change this color: https://github.com/Robdel12/DropKick/blob/master/lib/css/dropkick.scss#L20 and rebuild the CSS

**Comment by benlevywebdesign** [comment]
![screenshot_2015-08-29-23-43-18 2](https://cloud.githubusercontent.com/assets/6495066/9566064/835abe80-4ea8-11e5-9722-10ac77d73a0f.png)


This is what I am taking about when i say a light blue background on tap. I've inspected everything and can't find what it is

Thanks,
Ben!
