### ISSUE TITLE
Trigering change event fails on Internet Explorer

### ISSUE THREAD

**Issue by Korri** [Robdel12/DropKick#314]
Looks like `dispatchEvent` does not work on Internet Explorer (on the 11 version at least), so the line `this.data.select.dispatchEvent( new CustomEvent("change", {bubbles: this.data.settings.bubble}));` fails with an error `SCRIPT445` error.

Edit: Removed out of place example.

**Comment by Korri** [comment]
This solved it for me:
```javascript
                if ( !disabled ) {
                    var evt = document.createEvent("HTMLEvents");
                    evt.initEvent("change", this.data.settings.bubble, true);
                    this.data.select.dispatchEvent(evt);
                }
```

**Comment by Robdel12** [comment]
Hey @Korri, I wasn't able to reproduce this error. [Here's a small screen recording](http://recordit.co/ut3b2zNSvU).

I'm going to close this but feel free to raise the issue again if you're still having the problem.

**Comment by loayza** [comment]
I know this is old stuff but I just have the same issue, but in IE 10. [Screenshot](https://cloud.githubusercontent.com/assets/3081878/17631354/b3b49094-60bb-11e6-88f8-3d16d714b09c.png).

@Korri's tweak solves it.

**Comment by Robdel12** [comment]
Can you post what your dropkick constructor looks like?

**Comment by porchlight** [comment]
Ran into this issue today, which is the same as https://github.com/Robdel12/DropKick/issues/321

Can confirm that @Korri 's code fixed it.

**Comment by Robdel12** [comment]
Sorry for the late reply. Looks like #353 will clean this up.
