### ISSUE TITLE
Empty select causes crash

### ISSUE THREAD

**Issue by Korri** [Robdel12/DropKick#315]
When called on a `<select>` with no `<option/>` tags dropkick causes an unhandled error:

`Uncaught TypeError: Cannot read property 'className' of undefined`

I know it is not something that should happen, but it can be pretty anoying as it kills any remaining javascript on the page.

**Comment by Robdel12** [comment]
Thanks for the issue! I'd like to handle this error a little better so it doesn't lill the rest of the JS on the page. Hopefully there will be time over the holiday break to take care of this :P
