### ISSUE TITLE
DropKick errors out when not mounted on mobile.

### ISSUE THREAD

**Issue by nrdobie** [Robdel12/DropKick#318]
When using the `new Dropkick(elem, {mobile: false})` configuration, DropKick will crash when calling methods that manipulate Dropkick like `.refresh()` and `.dispose()` on mobile. DropKick will attempt to remove itself even though it was never mounted causing an error.

The hack fix I found was to check that `dropkick.data.elem.parentNode` has a value before calling any of the DropKick functionality. This check should probably be added to DropKick before performing DOM manipulations or offer a function for users to easily check if DropKick was actually mounted.

**Comment by nrdobie** [comment]
Another option would be to just have DropKick sto

**Comment by Robdel12** [comment]
Hi @nrdobie! I can't replicate this issue. Here is a JSBin I used to try and replicate it: http://jsbin.com/zeruhum/2/edit?html,js,output

**Comment by Robdel12** [comment]
After doing more digging it seems this was fixed with #310
