### ISSUE TITLE
IE11 Issue: Change event.

### ISSUE THREAD

**Issue by gautam2688** [Robdel12/DropKick#321]
We are facing problem in IE 11 When user select any value containing large text. Please help me ASAP.'

![dropkik2](https://cloud.githubusercontent.com/assets/17717969/13627969/685b27e4-e5f4-11e5-8dfe-7a4d87ee6046.png)
![dropkit](https://cloud.githubusercontent.com/assets/17717969/13627970/686677e8-e5f4-11e5-85f8-21ba767dae9a.png)

**Comment by Robdel12** [comment]
Hi! Can you tell me what version of dropkick? And possibly provide a [JSBin](http://jsbin.com/?html,css,js,output)?

**Comment by JoshuaJones** [comment]
The bug happens when using browserify and specifying `var Dropkick = require('dropkickjs');`

If you point to `dropkick.2.1.7.min.js` in `build/js`, the error is resolved.
