### ISSUE TITLE
Classes added to the combobox are removed on select

### ISSUE THREAD

**Issue by Florian-R** [Robdel12/DropKick#337]
### Version of Dropkick:
2.1.8

### Expected Behavior
Classes setted by the user aren't removed

### Actual Behavior
Dropkick remove user supplied classes

### Steps To Reproduce:
1. Add a class to the `.dk-selected` div
2. Pick a value
3. Class is removed

### JSBin / Example repo / Failing test:
http://jsbin.com/polayojoru/1/edit?html,css,js,output

I wanna use specific className to target the `.dk-selected` element (mainly to have consistency with my others input), but [this line](https://github.com/Robdel12/DropKick/blob/e1210dcbfb80176434511f65459a092401205b7b/lib/dropkick.js#L805) remove them.

My best bet will be to use `_.addClass` instead of setting directly here. Another approach will be to pass this as an option, but I suspect this could lead to API bloat (e.g. users wanting to customize all the classes). Maybe we should do both, don't know what are you preferred approach.

Let me know WDYT, and I'll fire a PR quickly.

Thanks!

**Comment by wwilsman** [comment]
Dropkick allows you to add classes to the select and the individual options to allow for some extra customizations.

Example:
http://jsbin.com/bivudi/edit?html,css,js,output

The reason that line removes the old classes is so previous classes added from other options aren't persisted when the selected option changes.

**Comment by Florian-R** [comment]
Ah, I missed that in the docs. Thanks @wwilsman

**Comment by Florian-R** [comment]
Think I have closed this too soon. On my bin, the `input` class is attached to the `dk-selected` div.
On yours, it's attached to the root element (`dk-select`). It cause some buggy styling in my case as I have some `:focus`on `.input`.

One solution could be to pass the `option.className` to the root element instead (so we can also always reattach the select className to preserve current behavior), but this is a breaking change.

For now, I simply reattach the class on the change handler, a bit ugly but it does the job.

Reopening in case you want to chime in, feel free to close if you don't think there's need for change.

**Comment by wwilsman** [comment]
I'm going to close this as I feel you could typically solve this by just using a different selector to target Dropkick specifically.

Where you might currently have something like this:
````css
.input:focus {
  /* ... */
}
````

You could add a similar class to Dropkick and target it this way:
````css
.input:focus,
.dk-input .dk-selected:focus {
  /* ... */
}
````

Of course, this might not always be so easy if you're using a CSS framework. In either case, I don't feel like this is a bug as adding classes to the generated markup after initialization was never intended. If you must, I think reattaching it in the change handler as you did should work fine.
