### ISSUE TITLE
Select with all options disabled breaks

### ISSUE THREAD

**Issue by mlpm0** [Robdel12/DropKick#339]
### Version of Dropkick:

2.1.9
### Expected Behavior

A new dropkick dropdown element should appear with all options disabled
### Actual Behavior

Dropkick shows error:
"Uncaught TypeError: Cannot read property 'className' of undefined"
### Steps To Reproduce:
1. In a select element, make all options disabled <option disabled>
2. Initialize dropkick on select element
3. "Uncaught TypeError: Cannot read property 'className' of undefined"
### JSBin / Example repo / Failing test:

http://jsbin.com/quwizinavo/edit?html,css,js,output

**Comment by Robdel12** [comment]
Hi! Thanks for the issue & sorry it took more than a year for a reply :/ 

Looks like v2.2.x doesn't suffer from this issue, so I'm going to close. 

(JSBin for reference: http://jsbin.com/didewiduhu/1/edit?html,js,output)
