### ISSUE TITLE
This isn't really an issue, but

### ISSUE THREAD

**Issue by iamshawnrice** [Robdel12/DropKick#343]
http://imgur.com/aq7hZ2q made me laugh harder than anything else this week. And I immediately thought of you.

Happy New Year man. I hope you guys are doing great.

**Comment by Robdel12** [comment]
Uhhhhmazing hahaahahahah! Pretty accurate for lil wayne too. 

Happy New Year to you too! Nothing I can complain about on my end. Hope everything is going well for you too!
