### ISSUE TITLE
Not working on IE 11

### ISSUE THREAD

**Issue by quienti** [Robdel12/DropKick#350]
### Expected Behavior

Working on IE 11

### Actual Behavior

Not working on IE 11, I have not problem with another browser
![untitled 1](https://user-images.githubusercontent.com/7326954/30603425-b45e446a-9d67-11e7-876a-085dc81f1aec.jpg)

Impossible to change select.

**Comment by quienti** [comment]
After investigate, I have find a solution

Change this line 
https://github.com/Robdel12/DropKick/blob/master/src/dropkick.js#L604

With

`//this.data.select.dispatchEvent( new CustomEvent("change", {bubbles: this.data.settings.bubble}));`
`var evt = document.createEvent("HTMLEvents");`
`evt.initEvent("change", true, true);`
`this.data.select.dispatchEvent(evt);`

And It's working find

**Comment by Robdel12** [comment]
Thanks for the bug! I'm going to see if I can get to this tonight or over the weekend
